version: "3"

services:
  web:
    container_name: kostkater-container
    image: kostkater-image:development
    build: .
    command: sh -c "uvicorn main:app --reload --port=80 --host=0.0.0.0"
    env_file:
      - .env.development
    ports:
      - 80:80
    volumes:
      - .:/app
